config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :admins, skip: :registration

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  apipie

  # resources :rates, only: %i[index]

  get '/:name', to: 'rates#index'

  namespace :api do
    namespace :v1 do
      resources :rates, only: %i[] do
        get '/current_weather/:name', on: :collection, to: 'rates#current_weather'
        get '/weathers/:name', on: :collection, to: 'rates#weathers'
        get '/our_weathers/:name', on: :collection, to: 'rates#our_weathers'
        get '/global_rates/:name', on: :collection, to: 'rates#global_rates'
      end

      get '/cities',to: 'cities#take_all'
    end
  end

  authenticate :admin do
    mount Sidekiq::Web => '/admins/sidekiq'
    mount PgHero::Engine => '/admins/pghero'
  end

  root 'rates#index'
  
  namespace :admins do
    resources :logs, only: :index do
      get :open, on: :collection
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_deviation.rb
class AverageDeviation < ApplicationRecord
  validates :days, :average, :count, presence: true
  validates :source_id, uniqueness: { scope: %i[days location_id] }

  belongs_to :source
  belongs_to :location
end

app/models/factual_weather.rb
class FactualWeather < ApplicationRecord
  validates :parsed_at, :temperature, presence: true

  belongs_to :location

  scope :by_period, ->(from, to) { where('parsed_at >= :from AND parsed_at <= :to', from: from, to: to) }
end

app/models/global_rate.rb
class GlobalRate < ApplicationRecord
  validates :days, :true_strike, :strike_count, presence: true
  validates :source_id, uniqueness: { scope: %i[days location_id] }

  belongs_to :source
  belongs_to :location
end

app/models/location.rb
class Location < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :rates
  has_many :sources, through: :rates
  has_many :factual_weathers, dependent: :destroy
  has_many :temperatures, dependent: :destroy
  has_many :predictions, dependent: :destroy
  has_many :global_rates, dependent: :destroy
  has_many :average_deviations, dependent: :destroy
end

app/models/prediction.rb
class Prediction < ApplicationRecord
  validates :days, :parsed_at, :prediction_time, :predicted_temperature, presence: true

  belongs_to :location
  belongs_to :source

  scope :by_period, ->(from, to) { where('parsed_at >= :from AND parsed_at <= :to', from: from, to: to) }
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :source
  belongs_to :location
end

app/models/source.rb
class Source < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :rates
  has_many :temperatures
  has_many :locations, through: :rates
  has_many :predictions
  has_many :global_rates, dependent: :destroy
  has_many :average_deviations, dependent: :destroy

  scope :without_our, -> { where.not(name: %w[Meteo-stat Meteo-stat(normal)]) }
  scope :five_days, -> { all }
  scope :ours, -> { where(name: %w[Meteo-stat Meteo-stat(normal)]) }
end

app/models/temperature.rb
class Temperature < ApplicationRecord
  validates :parsed_at, :temperature, presence: true

  belongs_to :location
  belongs_to :source

  scope :by_period, ->(from, to) { where('parsed_at >= :from AND parsed_at <= :to', from: from, to: to) }
end

app/controllers/admins/logs_controller.rb
module Admins
  class LogsController < ApplicationController
    before_action :authenticate_admin!

    def index
      logs
    end

    def open
      @messages = Logs::Filter.call(params[:name], params[:filter])

      respond_to do |format|
        format.html { render 'open.html.erb', name: params[:name] }
        format.js {}
      end
    end

    def logs
      @logs ||= Dir.open(ENV['PATH_TO_PARSERS_LOG']).to_a.map { |item| item.split('.').first if item.match?(/\.log$/) }.compact
    end
  end
end

app/controllers/api/v1/application_controller.rb
module Api
  module V1
    class ApplicationController < ActionController::API
    end
  end
end

app/controllers/api/v1/cities_controller.rb
module Api
  module V1
    class CitiesController < ApplicationController
      api :GET, '/v1/cities', 'Get array of cities'
      returns code: 200, desc: 'array of cities'
      def take_all
        render json: Location.select(:id, :name).pluck(:name)
      end
    end
  end
end

app/controllers/api/v1/rates_controller.rb
module Api
  module V1
    class RatesController < ApplicationController
      api :GET, '/v1/rates/current_weather/:name', 'Get current weather from best source of today'
      param :name, String, desc: 'City name'
      returns code: 200, desc: 'current weathers' do
        property :temperature, Float, desc: 'current temperature'
        property :wind_speed, Float, desc: 'current wind speed'
        property :wind_direction, String, desc: 'current wind direction'
        property :humidity, Float, desc: 'current humidity'
        property :pressure, Float, desc: 'current pressure'
        property :source, String, desc: 'name of source'
      end

      def current_weather
        render json: Weathers::DetectCurrentWeather.call(location: location)
      end

      api :GET, '/v1/rates/weathers/:name', 'Get predicted weathers from other sources'
      param :name, String, desc: 'City name'
      returns code: 200, desc: 'hash of predicted weathers from other sources' do
        property :weathers, Hash do
          property :weather, Hash do
            property :temperature, Float, desc: 'predicted temperature'
          end
        end
      end

      def weathers
        render json: Weathers::Detect.call(location: location)
      end

      api :GET, '/v1/rates/our_weathers/:name', 'Get predicted weathers from our sources'
      param :name, String, desc: 'City name'
      returns code: 200, desc: 'hash of predicted weathers from our sources' do
        property :weathers, Hash do
          property :weather, Hash do
            property :temperature, Float, desc: 'predicted temperature'
          end
        end
      end
      def our_weathers
        render json: Weathers::GetOurWeather.call(location: location)
      end

      api :GET, '/v1/rates/global_rates/:name', 'Get rates for sources and location'
      param :name, String, desc: 'City name'
      returns code: 200, desc: 'hash of global rates for each source' do
        property :rates, Hash do
          property :source_rates, Hash do
            property :rate, Float, desc: 'rate of source'
          end
        end
      end
      def global_rates
        render json: Rates::Load.call(location)
      end

      private

      def location
        @location ||= Location.find_by(name: params[:name].capitalize) || Location.take
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  def index
    @best_source = Weathers::DetectBestSource.call(location: location)
    @weathers = Weathers::Detect.call(location: location)
    @sources = Source.five_days
    @our_weathers = Weathers::GetOurWeather.call(location: location)
  end

  private

  def location
    @location ||= Location.find_by(name: params[:name].capitalize) || Location.take
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def day_name(day_number)
    return t('headers.today') if day_number.to_i.zero?

    day_number.to_date.strftime('%d %B')
  end
end

app/views/admins/logs/_message.html.erb
<%= message %><br>

app/views/admins/logs/index.html.erb
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Burning Buttons</a>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <%= link_to 'Sign Out', destroy_admin_session_path, method: :delete, class: "nav-link" %>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
              Logs
            </a>
          </li>
      </div>
    </nav>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Logs</h1>
      </div>
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <ul class="nav">
          <% @logs.each do |log| %>
            <li class="nav-item">
              <%= link_to log, '#', id: 'log_' + log, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="nav log_buttons">
        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="info" id="infoCheck" checked>
          <label class="form-check-label" for="infoCheck">
            show info messages
          </label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="warn" id="warnCheck" checked>
          <label class="form-check-label" for="warnCheck">
            show warn messages
          </label>
        </div>
      </div>
      <div class="log_container">

      </div>


      <canvas class="my-4 w-100 chartjs-render-monitor" id="myChart" width="1078" height="455" style="display: block; width: 1078px; height: 455px;"></canvas>

    </main>
  </div>
</div>
<h1>Logs Page</h1>
<% @logs.each do |log| %>
  <h2><%= link_to log, open_admins_logs_path(name: log) %></h2>
<% end %>

app/views/admins/logs/open.html.erb
<div class="log_name"><%= params[:name] %></div>

<div class="log_container">
  <% @messages.each do |message| %>
    <%= message %><br>
  <% end %>
</div>
<div class="nav log_buttons">
  <div class="form-check">
    <input class="form-check-input" type="checkbox" value="info" id="infoCheck" checked>
    <label class="form-check-label" for="infoCheck">
      show info messages
    </label>
  </div>
  <div class="form-check">
    <input class="form-check-input" type="checkbox" value="warn" id="warnCheck" checked>
    <label class="form-check-label" for="warnCheck">
      show warn messages
    </label>
  </div>
</div>

app/views/admins/logs/open.js.erb
$('.log_container').html('<%= j render partial: "message", collection: @messages, as: :message %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WrpWeb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rates/_day_tab.html.erb
<li class="nav-item">
  <a class="nav-link <%= 'active' if day_number.to_i.zero? %>" id="forecast-<%= day_number %>-tab" data-toggle="tab" href="#forecast-<%= day_number %>" role="tab">
    <%= day_name(day_number) %>
  </a>
</li>

app/views/rates/_global_rates.html.erb
<% @sources %>

<table class="table">
  <thead>
    <tr scope="col"><h3>Forecast Accuracy Rate</h3></tr>
    <tr>
      <th scope="col">Source</th>
      <th scope="col">Current Temperature</th>
      <th scope="col">+1 Day</th>
      <th scope="col">+2 Days</th>
      <th scope="col">+3 Days</th>
      <th scope="col">+4 Days</th>
      <th scope="col">+5 Days</th>
    </tr>
  </thead>
  <tbody>
    <% @sources.each do |s| %>
      <tr>
        <th scope="row"><%= s.name %></th>
        <% s.global_rates.where(location_id: @location.id).order(:days).each do |gr| %>
          <td><%= "#{gr.rate.round(3)} (#{gr.true_strike}/#{gr.strike_count})"%></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rates/_our_predictions.html.erb
<li class="nav-item">
  <a class="nav-link <%= 'active' if day_number.to_i.zero? %>" id="our_forecast-<%= day_number %>-tab" data-toggle="tab" href="#our_forecast-<%= day_number %>" role="tab">
    <%= day_name(day_number) %>
  </a>
</li>

app/views/rates/_our_temperatures.html.erb
<div class="tab-pane fade <%= 'show active' if day_number.to_i.zero? =%>" id="our_forecast-<%= day_number %>" role="tabpanel" aria-labelledby="our_forecast-<%= day_number %>-tab">


    <p class="mt-4"><%= t('views.weathers.provided_by') + ': ' + (data[:source] || t('views.error.source_no t_found')) %></p>

    <%- data.first(4).each do |hour, weather| %>
      <%- if weather.class == Hash && weather[:temperature].present? && hour % 6 == 0 %>
        <div class="d-inline-block hour-forecast mr-5">
          <div class="time">
            <%= (Date.today + hour.hours).strftime('%H:%M') %>
          </div>
          <div class="temperature mt-2">
            <%= weather[:temperature] < 0 ? weather[:temperature] : "+#{weather[:temperature]}"  %>°С
          </div>
        </div>
      <%- end %>
    <%- end %>
</div>

app/views/rates/_temperatures.html.erb
<div class="tab-pane fade <%= 'show active' if day_number.to_i.zero? =%>" id="forecast-<%= day_number %>" role="tabpanel" aria-labelledby="forecast-<%= day_number %>-tab">
    <p class="mt-4"><%= t('views.weathers.provided_by') + ': ' + (data[:source] || t('views.error.source_no t_found')) %></p>

    <%- data.first(4).each do |hour, weather| %>
      <%- if weather.class == Hash && weather[:temperature].present?  && hour % 6 == 0 %>
        <div class="d-inline-block hour-forecast mr-5">
          <div class="time">
            <%= (Date.today + hour.hours).strftime('%H:%M') %>
          </div>
          <div class="temperature mt-2">
            <%= weather[:temperature] < 0 ? weather[:temperature] : "+#{weather[:temperature]}"  %>°С
          </div>
        </div>
      <%- end %>
    <%- end %>
</div>

app/views/rates/index.html.erb
<div class="p-3">

  <h2>Current Temperature</h2>
  <p class="mt-4"><%= "Provided by: #{@best_source.name}" %></p>
  <div class="mt 2">Temperature <%= @location.temperatures.where(source: @best_source).last&.temperature %>°С</div>

  <br>
  <h2> Our Forecast </h2>
  <ul class="nav nav-tabs" id="our_forecast-tabs" role="tablist">
    <%= render 'rates/our_predictions', day_number: '0' %>
    <%- @our_weathers.except("#{Date.today}").each do |day_number, _source_data| %>
      <%= render 'rates/our_predictions', day_number: day_number %>
    <%- end %>
  </ul>

  <div class="tab-content" id="our_forecast-content">

    <%= render 'rates/our_temperatures', day_number: '0', data: @our_weathers["#{Date.today}"] %>

    <%- @our_weathers.except("#{Date.today}").each do |day_number, data| %>
      <%= render 'rates/our_temperatures', day_number: day_number, data: data %>
    <%- end %>
  </div>

  <br>
  <h2> Forecast </h2>

  <ul class="nav nav-tabs" id="forecast-tabs" role="tablist">
    <%= render 'rates/day_tab', day_number: '0' %>

    <%- @weathers.except("#{Date.today}").each do |day_number, _source_data| %>
      <%= render 'rates/day_tab', day_number: day_number %>
    <%- end %>
  </ul>

  <div class="tab-content" id="forecast-content">

    <%= render 'rates/temperatures', day_number: '0', data: @weathers["#{Date.today}"] %>

    <%- @weathers.except("#{Date.today}").each do |day_number, data| %>
      <%= render 'rates/temperatures', day_number: day_number, data: data %>
    <%- end %>
  </div>

  <br>
  <div class="tab-content" id="rates-content">
    <%= render 'rates/global_rates' %>
  </div>
</div>